export const RESERVATION_FAIL = 'RESERVATION_FAIL'
export const RESERVATION_REQUEST = 'RESERVATION_REQUEST'
export const RESERVATION_SUCCESS = 'RESERVATION_SUCCESS'

export const RESERVATION_LOGOUT = 'RESERVATION_LOGOUT'

export const RESERVATION_LOGIN_FAIL = 'RESERVATION_LOGIN_FAIL'
export const RESERVATION_LOGIN_REQUEST = 'RESERVATION_LOGIN_REQUEST'
export const RESERVATION_LOGIN_SUCCESS = 'RESERVATION_LOGIN_SUCCESS'

export const RESERVATION_ADD_FAIL = 'RESERVATION_ADD_FAIL'
export const RESERVATION_ADD_REQUEST = 'RESERVATION_ADD_REQUEST'
export const RESERVATION_ADD_SUCCESS = 'RESERVATION_ADD_SUCCESS'

export const RESERVATION_REGISTER_FAIL = 'RESERVATION_REGISTER_FAIL'
export const RESERVATION_REGISTER_REQUEST = 'RESERVATION_REGISTER_REQUEST'
export const RESERVATION_REGISTER_SUCCESS = 'RESERVATION_REGISTER_SUCCESS'

export const RESERVATION_DETAILS_REQUEST = 'RESERVATION_DETAILS_REQUEST'
export const RESERVATION_DETAILS_SUCCESS = 'RESERVATION_DETAILS_SUCCESS'
export const RESERVATION_DETAILS_FAIL = 'RESERVATION_DETAILS_FAIL'
export const RESERVATION_DETAILS_RESET = 'RESERVATION_DETAILS_RESET'

export const RESERVATION_UPDATE_PROFILE_REQUEST = 'RESERVATION_UPDATE_PROFILE_REQUEST'
export const RESERVATION_UPDATE_PROFILE_SUCCESS = 'RESERVATION_UPDATE_PROFILE_SUCCESS'
export const RESERVATION_UPDATE_PROFILE_FAIL = 'RESERVATION_UPDATE_PROFILE_FAIL'

export const RESERVATION_LIST_REQUEST = 'RESERVATION_LIST_REQUEST'
export const RESERVATION_LIST_SUCCESS = 'RESERVATION_LIST_SUCCESS'
export const RESERVATION_LIST_FAIL = 'RESERVATION_LIST_FAIL'
export const RESERVATION_LIST_RESET = 'RESERVATION_VATION_LIST_RESET'

export const RESERVATION_DELETE_REQUEST = 'RESERVATION_DELETE_REQUEST'
export const RESERVATION_DELETE_SUCCESS = 'RESERVATION_DELETE_SUCCESS'
export const RESERVATION_DELETE_FAIL = 'RESERVATION_DELETE_FAIL'

export const RESERVATION_UPDATE_REQUEST = 'RESERVATION_UPDATE_REQUEST'
export const RESERVATION_UPDATE_SUCCESS = 'RESERVATION_UPDATE_SUCCESS'
export const RESERVATION_UPDATE_FAIL = 'RESERVATION_UPDATE_FAIL'
export const RESERVATION_UPDATE_RESET = 'RESERVATION_UPDATE_RESET'
